name: build app
on:
    push:
        branches:
            - master
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
                  cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Copy config.json
              run: |
                cp ./resources/js/config.json.example ./resources/js/config.json
            - name: Build static project
              run: npm run prod-laravel
            - name: Archive build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: dist
